library(dplyr)
library(lubridate)
pdata <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?", stringsAsFactors = FALSE)
dpldata <- tbl_df(pdata)
dpldata <- mutate(dpldata, Date = as.Date(Date, "%d/%m/%Y"))
dpldata <- filter(dpldata, Date >= "2007-02-01" & Date < "2007-02-03")
dpldata <- mutate(dpldata, datetime = paste(wday(Date, label = TRUE, locale = Sys.setlocale("LC_TIME", "us")), Date, Time))
dpldata <- mutate(dpldata, fdt = as.POSIXct(strptime(datetime, "%a %Y-%m-%d %H:%M:%S")))
png("plot2.png", width = 480, height = 480, units = "px")
with(dpldata, plot(fdt, Global_active_power, type = "l", xlab = "", ylab = "Global Active Power (kilowatts)"))
dev.off()
